### ISSUE TITLE
README refers to 0.0.4 but should be 0.0.5 for current?

### ISSUE THREAD

**Issue by vjcitn** [anvilproject/anvil-docker#15]

**Comment by gpcarr** [comment]
actually it should be 0.0.6, looks like 0.0.5 was missed. I'll update this tomorrow morning

**Comment by gpcarr** [comment]
README for base image also needs to be updated, I'll make sure to do that tomorrow as well

**Comment by gpcarr** [comment]
been out sick all week, going to set up a PR now to bump versions in README
